//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Job_Seeker.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register
    {
        public int Userid { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public Nullable<bool> IsSuperAdmin { get; set; }
        public string ResetPasswordCode { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
